name: Build and deploy documentation site
on:
  workflow_dispatch:
  push:
    branches:
      - antora
concurrency:
  group: github-pages
  cancel-in-progress: false
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v3


      #- name: Install Just 1.38.0
      #run: pip install rust-just==1.38.0
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.20.0'
      - name: Install Antora with the Antora Lunr Extension
        run: npm i antora @antora/lunr-extension @sntke/antora-mermaid-extension asciidoctor-kroki @djencks/asciidoctor-mathjax
      - name: Install Antora dependencies
        run: npm i      
      - name: Generate site
        run: npx antora antora-playbook.yml
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4